{% set name = "mss" %}
{% set version = "7.0.0" %}

package:
  name: python-mss
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f658f89e92b58f22c295d6d8fe73d2469de29001da32716e744b564bc6a07622

build:
  number: 0
  noarch: python
  entry_points:
    - mss=mss.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - mss
  commands:
    - mss --help
    - mss --version

about:
  home: https://github.com/BoboTiG/python-mss
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An ultra fast cross-platform multiple screenshots module in pure python using ctypes.
  description: |
    Python 3.6+, PEP8 compliant, no dependency and thread-safe.
    Very basic, it will grab one screen shot by monitor or a screen shot of all monitors and save it to a PNG file.
    But you can use PIL and benefit from all its formats (or add yours directly).
    Integrate well with Numpy and OpenCV.
    It could be easily embedded into games and other software which require fast and platform optimized methods to grab screen shots (like AI, Computer Vision).
    MSS stands for Multiple Screen Shots.
  doc_url: https://python-mss.readthedocs.io
  dev_url: https://github.com/BoboTiG/python-mss

extra:
  recipe-maintainers:
    - BoboTiG
