{% set name = "mss" %}
{% set version = "10.0.0" %}

package:
  name: python-mss
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d903e0d51262bf0f8782841cf16eaa6d7e3e1f12eae35ab41c2e318837c6637f

build:
  number: 1
  noarch: python
  entry_points:
    - mss=mss.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - mss
  commands:
    - mss --help
    - mss --version

about:
  home: https://github.com/BoboTiG/python-mss
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An ultra fast cross-platform multiple screenshots module in pure python using ctypes.
  description: |
    Python 3.9+, PEP8 compliant, no dependency, and thread-safe.
    Very basic, it will grab one screenshot by monitor or a screenshot of all monitors and save it to a PNG file.
    But you can use PIL and benefit from all its formats (or add yours directly).
    Integrate well with Numpy and OpenCV.
    It could be easily embedded into games and other software which require fast and platform optimized methods to grab screen shots (like AI, Computer Vision).
    MSS stands for Multiple ScreenShots.
  doc_url: https://python-mss.readthedocs.io
  dev_url: https://github.com/BoboTiG/python-mss

extra:
  recipe-maintainers:
    - BoboTiG
